# Generated by Django 5.0.1 on 2024-01-18 16:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('secondname', models.CharField(max_length=50, null=True, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('short_name', models.CharField(max_length=10, verbose_name='Сокращенное название')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='Сокращенное название')),
                ('full_name', models.CharField(max_length=50, verbose_name='Полное название')),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вместимость')),
                ('history', models.TextField(null=True, verbose_name='История')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperiense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Начало')),
                ('date_end', models.DateField(default=None, verbose_name='Конец')),
            ],
        ),
        migrations.CreateModel(
            name='Ligs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.countries', verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='Сокращенное название')),
                ('full_name', models.CharField(max_length=50, verbose_name='Полное название')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clubs.coaches', verbose_name='Тренер')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.countries', verbose_name='Страна')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.stadiums', verbose_name='Стадион')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('secondname', models.CharField(max_length=50, null=True, verbose_name='Отчество')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.countries', verbose_name='Страна')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.positions', verbose_name='Позиция')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.teams', verbose_name='Команда')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_match', models.DateTimeField(verbose_name='Дата матча')),
                ('goals_first_team', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Голы первой команды')),
                ('goals_second_team', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Голы второй команды')),
                ('minutes_left', models.IntegerField(default=90, verbose_name='Минут осталось')),
                ('minutes_add', models.IntegerField(default=0, verbose_name='Минут осталось')),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_matches', to='clubs.teams', verbose_name='Команда гостей')),
                ('host_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='clubs.teams', verbose_name='Команда хозяев')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStandings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
                ('number_win', models.IntegerField(default=0, verbose_name='Побед')),
                ('number_loose', models.IntegerField(default=0, verbose_name='Поражений')),
                ('number_draw', models.IntegerField(default=0, verbose_name='Ничей')),
                ('goal_differences', models.IntegerField(default=0, verbose_name='Разница мячей')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.ligs', verbose_name='Лига')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.seasons', verbose_name='Сезон')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.teams', verbose_name='Команда')),
            ],
        ),
        migrations.CreateModel(
            name='Judges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('secondname', models.CharField(max_length=50, null=True, verbose_name='Отчество')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('work_experiense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.workexperiense', verbose_name='Время работы')),
            ],
        ),
        migrations.AddField(
            model_name='coaches',
            name='work_experiense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.workexperiense', verbose_name='Время работы'),
        ),
    ]
