# Generated by Django 5.0.1 on 2024-01-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_countries_options_alter_judges_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judges',
            name='secondname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
