# Generated by Django 5.0.1 on 2024-01-18 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_judges_secondname'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='age',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='age',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
