# Generated by Django 5.0.1 on 2024-01-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_judges_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coaches',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AlterModelOptions(
            name='matches',
            options={'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='stadiums',
            options={'verbose_name': 'Стадион', 'verbose_name_plural': 'Стадионы'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='teamstandings',
            options={'verbose_name': 'Турнирная позиция', 'verbose_name_plural': 'Турнирные позиции'},
        ),
        migrations.AlterField(
            model_name='players',
            name='secondname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='short_name',
            field=models.CharField(max_length=20, verbose_name='Сокращенное название'),
        ),
    ]
