# Generated by Django 5.0.1 on 2024-01-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_coaches_options_alter_matches_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaches',
            name='secondname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
