# Generated by Django 5.0.1 on 2024-01-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_coaches_secondname'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение'),
        ),
    ]
