# Generated by Django 5.0.1 on 2024-01-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_coaches_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='teams',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение'),
        ),
    ]
