# Generated by Django 5.0.1 on 2024-01-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_players_image_teams_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ligs',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stadiums',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='full_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
