# Generated by Django 5.0.1 on 2024-01-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_countries_name_alter_ligs_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamstandings',
            options={'permissions': [('can_change_results_team_standings', 'Возможность изменять статистические данные команды')], 'verbose_name': 'Турнирная позиция', 'verbose_name_plural': 'Турнирные позиции'},
        ),
    ]
