# Generated by Django 5.0.1 on 2024-01-30 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_alter_teamstandings_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasons',
            name='name',
        ),
        migrations.AddField(
            model_name='seasons',
            name='begin_year',
            field=models.IntegerField(default=2023, help_text='Введите год', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Начало'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seasons',
            name='end_year',
            field=models.IntegerField(default=2024, help_text='Введите год', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Конец'),
            preserve_default=False,
        ),
    ]
