# Generated by Django 5.0.1 on 2024-02-08 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_favoriteteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='liga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='clubs.ligs', verbose_name='Лига'),
            preserve_default=False,
        ),
    ]
